apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: deployment-k8s-manifest
spec:
  type: NodePort
  selector:
    app: hello-service
  ports:
    - name: http
      port:       80      # porta interna del Service
      targetPort: http   # mappa al containerPort 8080
      nodePort:   30081  # porta su cui esporre dal nodo
