apiVersion: v1
kind: Service
metadata:
  name: response-service
  namespace: deployment-k8s-manifest
spec:
  type: NodePort
  selector:
    app: response-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30082
