apiVersion: apps/v1
kind: Deployment
metadata:
  name: response-service
  namespace: deployment-k8s-manifest
  labels:
    app: response-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: response-service
  template:
    metadata:
      labels:
        app: response-service
    spec:
      containers:
        - name: response-service
          imagePullPolicy: Always
          image: ghcr.io/francsco99/response-service/response-service:0.0.1-snapshot
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
