apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: deployment-k8s-manifest
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest
      command: ["sleep", "3600"]
      # Resource requests and limits to avoid noisy neighbor issues
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
  restartPolicy: OnFailure

