name: "Download JAR from GitHub Maven"
description: "Pull a JAR from GitHub Maven registry"

inputs:
  github-token:
    description: "GitHub token to access the Maven registry"
    required: true
  groupID:
    description: "Group ID of the JAR"
    required: true
  artifactID:
    description: "Artifact ID of the JAR"
    required: true
  version:
    description: "Version of the JAR"
    required: true
  outputDirectory:
    description: "Target directory where to save the JAR"
    required: true
  repository:
    description: "GitHub Maven repository URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven
      shell: bash

    - name: Setup Maven settings.xml
      run: |
        mkdir -p ~/.m2
        cp $GITHUB_WORKSPACE/.github/maven/settings.xml ~/.m2/settings.xml
      shell: bash
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Download JAR from GitHub Packages
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        mkdir -p ${{ inputs.outputDirectory }}
        mvn dependency:get \
          -Dartifact=${{ inputs.groupID }}:${{ inputs.artifactID }}:${{ inputs.version }} \
          -DrepoUrl=${{ inputs.repository }} \
          -DrepositoryId=github \
          -Ddest=${{ inputs.outputDirectory }}/app.jar \
          -Dtransitive=false \
          -s ~/.m2/settings.xml
      shell: bash
