name: "Download JAR from GitHub Maven"
description: "Download a JAR artifact from GitHub Maven registry"

inputs:
  github-token:
    description: "GitHub token to authenticate with the Maven registry"
    required: true
  groupID:
    description: "Group ID of the Maven artifact"
    required: true
  artifactID:
    description: "Artifact ID of the Maven artifact"
    required: true
  version:
    description: "Version of the Maven artifact"
    required: true
  outputDirectory:
    description: "Local directory to save the downloaded JAR"
    required: true
  repository:
    description: "Full GitHub Maven repository URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Maven CLI
      id: install-maven
      run: |
        sudo apt-get update && sudo apt-get install -y maven
      shell: bash

    - name: Configure Maven authentication
      id: setup-maven-settings
      run: |
        mkdir -p ~/.m2
        cp $GITHUB_WORKSPACE/.github/maven/settings.xml ~/.m2/settings.xml
      shell: bash
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Download JAR with Maven dependency plugin
      id: download-jar
      run: |
        mkdir -p ${{ inputs.outputDirectory }}
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.6.1:copy \
          -Dartifact=${{ inputs.groupID }}:${{ inputs.artifactID }}:${{ inputs.version }} \
          -DoutputDirectory=${{ inputs.outputDirectory }} \
          -DremoteRepositories=github::default::${{ inputs.repository }} \
          -Dtransitive=false \
          -s ~/.m2/settings.xml
      shell: bash
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
