name: "Package Container"
description: "Download JAR and Build & Push Docker image"
inputs:
  module:
    description: "Module name (and folder)"
    required: true
  image_registry:
    description: "Target image registry"
    required: true
  repo:
    description: "GitHub repo in format <owner>/<repo>"
    required: true
  group_id:
    description: "Maven groupId"
    required: true
  version:
    description: "Artifact version (default: LATEST)"
    required: false
    default: "LATEST"
  github_token:
    description: "GitHub token for Maven download"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download JAR
      uses: ./actions/jar-download
      with:
        github-token: ${{ inputs.github_token }}
        groupID: ${{ inputs.group_id }}
        artifactID: ${{ inputs.module }}
        version: ${{ inputs.version }}
        outputDirectory: ${{ inputs.module }}
        repository: https://maven.pkg.github.com/${{ inputs.repo }}

    - name: Build Docker image
      run: |
        OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/${OWNER}/${{ inputs.module }}:latest ${{ inputs.module }}
      shell: bash

    - name: Push Docker image
      run: docker push ${{ inputs.image_registry }}:latest
      shell: bash
