name: "Package Container"
description: "Build and push Docker image"

inputs:
  module:
    description: "Module folder"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set image tag
      id: vars
      run: |
        OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        echo "tag=ghcr.io/${OWNER}/${{ inputs.module }}:latest" >> $GITHUB_OUTPUT
      shell: bash

    - name: Docker login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Build Docker image
      run: docker build -t ${{ steps.vars.outputs.tag }} ${{ inputs.module }}
      shell: bash

    - name: Push Docker image
      run: docker push ${{ steps.vars.outputs.tag }}
      shell: bash
