name: "Package Container"
description: "Download JAR and Build & Push Docker image"
inputs:
  module:
    description: "Module name (and folder)"
    required: true
  artifact_id:
    description: "Artifact ID of the Maven JAR"
    required: true
  version:
    description: "Artifact version"
    required: true
  image_registry:
    description: "Target image registry"
    required: true
  repo:
    description: "GitHub repo in format <owner>/<repo>"
    required: true
  group_id:
    description: "Maven groupId"
    required: true
  github_token:
    description: "GitHub token for Maven download"
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug
      run: |
        ls -la
        ls -la ..
      shell: bash

    - name: Download JAR
      uses: ./.github/actions/jar-download
      with:
        github-token: ${{ inputs.github_token }}
        groupID: ${{ inputs.group_id }}
        artifactID: ${{ inputs.artifact_id }}
        version: ${{ inputs.version }}
        outputDirectory: ${{ inputs.module }}
        repository: https://maven.pkg.github.com/${{ inputs.repo }}
    
    - name: Debug
      run: |
        ls -la
        ls -la ..
      shell: bash

    - name: Show downloaded JAR
      run: ls -la ${{ inputs.module }}
      shell: bash

    - name: Find JAR file
      id: find-jar
      run: |
        # Cerca il jar nella cartella
        FILE=$(find "${{ inputs.module }}" -maxdepth 1 -type f -name "${{ inputs.artifact_id }}-*.jar")
        if [[ -z "$FILE" ]]; then
          echo "No jar found in ${{ inputs.module }}"
          exit 1
        fi
        JAR_NAME=$(basename "$FILE")
        echo "jar found: $JAR_NAME"
        echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV
      shell: bash


    - name: Pwd & Debug module directory
      run: |
        pwd
        ls -la ${{ inputs.module }}
      shell: bash

    - name: Create image tag (lowercase)
      run: |
        RAW_TAG="${{ inputs.image_registry }}/${{ inputs.module }}:${{ inputs.version }}"
        IMAGE_TAG=$(echo "$RAW_TAG" | tr '[:upper:]' '[:lower:]')
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.image_registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.module }}
        push: true
        tags: ${{ env.IMAGE_TAG }}
        build-args: |
          JAR_NAME=${{ env.JAR_NAME }}

    - name: Show Docker images
      run: docker images
      shell: bash
