replicaCount: 2

image:
  repository: ghcr.io/francsco99/response-service/response-service
  tag: "0.0.1-snapshot"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

serviceAccount:
  create: true
  name: ""  # Lascia vuoto così Helm usa il fullname del chart

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30082

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}

volumes: []

volumeMounts: []

livenessProbe: {}

readinessProbe: {}

securityContext: {}

podSecurityContext: {}

podAnnotations: {}

podLabels: {}

namespace: deployment-k8s-helm

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: null
