name: v1 Packaging dry

on:
  workflow_call:
    inputs:
      module:
        description: 'Name of module directory'
        required: true
        type: string
      artifact_id:
        description: 'Artifact ID of the JAR'
        required: true
        type: string
      version:
        description: 'Version of the artifact'
        required: true
        type: string
      branch:
        type: string
        required: true
      repository:
        description: 'GitHub Maven repo in format <owner>/<repo>'
        required: true
        type: string

jobs:
  packaging:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      FINAL_VERSION: ${{ inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract version from Git tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "FINAL_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and push image
        uses: ./.github/actions/package-container
        with:
          module: ${{ inputs.module }}
          artifact_id: ${{ inputs.artifact_id }}
          version: ${{ env.FINAL_VERSION }}
          group_id: com.example
          image_registry: ghcr.io/${{ github.repository_owner }}
          image_name: ${{ inputs.module }}
          repo: Francsco99/usvc-k8s
          github_token: ${{ secrets.GITHUB_TOKEN }}