name: v1 Packaging Application

run-name: Containerization of ${{ inputs.module }} from branch ${{ inputs.branch }}

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Select which module to package"
        required: true
        type: choice
        options:
          - all-modules
          - hello-service
          - response-service
      branch:
        description: "Git branch to use for packaging"
        required: true
        type: string
        default: main

jobs:
  packaging-single-module:
    name: Package single module
    if: ${{ inputs.module != 'all-modules' }}
    uses: ./.github/workflows/packaging-dry.yaml
    permissions:
      contents: read
      packages: write
    with:
      module: ${{ inputs.module }}
      artifact_id: ${{ inputs.module }}
      branch: ${{ inputs.branch }}
      repository: ${{ github.repository_owner }}/usvc-k8s
    secrets: inherit

  packaging-all-modules:
    name: Package all modules
    if: ${{ inputs.module == 'all-modules' }}
    strategy:
      max-parallel: 2
      matrix:
        module: [ "hello-service", "response-service" ]
    uses: ./.github/workflows/packaging-dry.yaml
    permissions:
      contents: read
      packages: write
    with:
      module: ${{ matrix.module }}
      artifact_id: ${{ matrix.module }}
      branch: ${{ inputs.branch }}
      repository: ${{ github.repository_owner }}/usvc-k8s
    secrets: inherit
