name: v1 Packaging Dry

on:
  workflow_call:
    inputs:
      module:
        description: 'Name of the module directory'
        required: true
        type: string
      artifact_id:
        description: 'Artifact ID of the JAR'
        required: true
        type: string
      branch:
        description: 'Git branch to package'
        required: true
        type: string
      repository:
        description: 'GitHub Maven repo in format <owner>/<repo>'
        required: true
        type: string

jobs:
  packaging:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        id: checkout-code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Authenticate Docker registry
        id: docker-login
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Package Container Action
        id: run-package-container
        uses: ./.github/actions/package-container
        with:
          module: ${{ inputs.module }}
          artifact_id: ${{ inputs.artifact_id }}
          group_id: com.example
          image_registry: ghcr.io/${{ github.repository_owner }}
          image_name: ${{ inputs.module }}
          repository: ${{ inputs.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
